hubrisone/hubrisone/urls.py
from django.contrib import admin
from django.urls import path,include

app_name = 'user'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('user/', include(('user.urls','user'), namespace='user')),
    path('management/', include(('management.urls','management'), namespace='management')),

]

hubrisone/user/urls.py
from django.urls import path,re_path
from user import views

app_name = 'user'

urlpatterns = [
    path('signup/', views.ProfileRecordView.as_view()),
    path('otp_verification/', views.VerificationView.as_view()),
    path('email_verification/', views.VerificationView.as_view()),
    path('pwd_reset_otp_verification/', views.VerificationView.as_view()),
    path('pwd_reset_email_verification/', views.VerificationView.as_view()),
    path('confirm_email/<email>/', views.VerificationView.as_view(), name= 'confirm_email'),
    path('check_email/', views.check_email, name= 'check_email'),
    path('check_mobile/', views.check_mobile, name= 'check_mobile'),
    path('password_reset/<email>/<password_reset>/', views.VerificationView.as_view(), name= 'password_reset_email'),
    path('login/', views.LogInView.as_view(),name='Login'),
    path('password_reset/', views.PasswordResetView.as_view(),name='Login'),
    path('check_username/', views.unique_username, name= 'check_username'),
]

hubrisone/templates/email_verification/email_confirmation.html
<p><b>Welcome To Hubrsione</b></p><br>
<p>Please confirm your email id by clicking on this</p>
{% if password_reset %}
<a href="http://{{domain}}{% url 'user:password_reset_email' email=email password_reset=password_reset%}">click here!!</a>
{% else %}
<a href="http://{{domain}}{% url 'user:confirm_email' email=email %}">click here!!</a>
{% endif %}
<p>Thankyou</p>